[package]
name = "bc-core"
version = "0.1.10"
edition = "2024"

[dependencies]
bc-types = { version = "0.1.0", path = "../bc-types" }
parking_lot = "0.12.5"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["sync", "rt", "macros", "time"] }
tracing = "0.1.44"
unicode-general-category = "1.0"
unicode-normalization = "0.1.25"
